# Site settings
author: Marcus Lau
title: Why did you decide to study Software Engineering?
header-img: img/home-bg.png
email: lau.marcus76@gmail.com
copyright_name: Marcus Lau
description: > # this means to ignore newlines until "baseurl:"
  kid wonder
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  marcusLau

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
